# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: envio-indexer
networks:
- id: 97
  start_block: 44528820
  contracts:
  - name: ProjectV1
    address:
    - 0x88be435E8a4cad3cE6E7ABE3468199F03b97B9B3
    handler: src/EventHandlers.ts
    events:
    - event: NewProject(uint256 indexed projectId, (bool,string,string,string,string,uint256,uint256,string,string,uint256) project)
    - event: SetSangha(uint256 indexed projectId, (address,address,address) project)
    - event: SetInitialLeader(uint256 indexed projectId, address initialLeader)
  - name: TreasuryV1
    address:
    - 0xD6dffF953AF507C7934F431d7b020d7C253377c3
    handler: src/EventHandlers.ts
    events:
    - event: CollateralVote(address indexed token, address voter, bool agree)
    - event: CollateralVotingAction(address indexed token, bool agree)
    - event: CollateralVotingInit(address indexed initializer, address indexed token, uint8 decimals, address feed, uint8 feedDecimals)
    - event: Mint(uint256 indexed projectId_, address ownershipToken, uint256 ownershipAmount, address to, uint256 usdAmount, address collateral, uint256 collateralAmount)
    - event: SetProject(uint256 indexed projectId, uint256 tokenAmount, uint256 usdAmount)
  - name: CashierV1
    address:
    - 0x51AED4dC4F45125Db25B5D7FF141D528e8A853B3
    handler: src/EventHandlers.ts
    events:
    - event: Redeem(address indexed check, address indexed collateral, address to, uint256 usdAmount, uint256 collateralAmount)
    - event: SetProject(uint256 indexed projectId)
  - name: ActV1
    address:
    - 0x959f18544660b8D144D82028faF04d0AD95E9a85
    handler: src/EventHandlers.ts
    events:
    - event: CancelTask(uint256 indexed projectId, uint256 indexed taskId, string payload)
    - event: CompleteTask(uint256 indexed projectId, uint256 indexed taskId, address contributor, string payload)
    - event: NewTask(uint256 indexed projectId, uint256 indexed taskId, uint256 checkAmount_, string payload)
    - event: SetProject(uint256 indexed projectId)
rollback_on_reorg: false
